# Generated by Django 5.1.7 on 2025-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sellingchannel",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
