# Generated by Django 5.1.7 on 2025-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_taxregion_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellingchannel",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="taxrate",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the tax rate", null=True
            ),
        ),
    ]
