# Generated by Django 5.1.7 on 2025-04-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0005_alter_sellingchannel_options_taxrate_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrate",
            name="tax_regions",
            field=models.ManyToManyField(related_name="rates", to="pricing.taxregion"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="tax_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_rates",
                to="pricing.taxregion",
            ),
        ),
    ]
