# Generated by Django 5.1.7 on 2025-04-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0006_taxrate_tax_regions_alter_taxrate_tax_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxrate",
            options={"ordering": ["tax_code"]},
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="tax_region",
        ),
    ]
