# Generated by Django 5.1.7 on 2025-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0008_taxrateprofile_code_taxrateprofile_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrateprofile",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
    ]
