# Generated by Django 5.1.7 on 2025-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0009_alter_taxrateprofile_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrateprofile",
            name="code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
