# Generated by Django 5.1.7 on 2025-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_kitcomponent_product_productattributemultivalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_status',
            field=models.CharField(
                choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')],
                db_index=True,
                default='DRAFT',
                help_text='Current publication status of the product',
                max_length=10
            ),
        ),
    ]
