# Generated by Django 5.1.7 on 2025-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attributes", "0006_attribute_is_active"),
        ("products", "0003_auto_20250410_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="attribute_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups whose attributes should be initially displayed",
                related_name="products",
                to="attributes.attributegroup",
            ),
        ),
    ]
