# Generated by Django 5.1.7 on 2025-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attributes", "0006_attribute_is_active"),
        ("products", "0004_product_attribute_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variant_defining_attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Attributes used to define variants for this product",
                limit_choices_to={"use_for_variants": True},
                related_name="defines_variants_for",
                to="attributes.attribute",
            ),
        ),
    ]
