# Generated by Django 5.1.7 on 2025-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_variant_defining_attributes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("client_id", "slug")},
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
