# Generated by Django 4.2.20 on 2025-04-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_variant_physical_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["product", "variant", "sort_order"]},
        ),
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="division",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="divisions/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="subcategories/"),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("product__isnull", False), ("variant__isnull", True)),
                    models.Q(("product__isnull", True), ("variant__isnull", False)),
                    _connector="OR",
                ),
                name="product_xor_variant",
            ),
        ),
    ]
