# Generated by Django 5.1.7 on 2025-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attributes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_filterable',
            field=models.BooleanField(default=False),
        ),
    ]
