# Generated by Django 5.1.7 on 2025-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attributes", "0002_add_required_filterable_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='show_on_pdp',
            field=models.BooleanField(default=True),
        ),
    ]
