# Generated by Django 5.1.7 on 2025-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attributes", "0004_rename_display_on_pdp_to_show_on_pdp"),
    ]

    operations = [
        # This was supposed to add is_active field to Attribute model,
        # but the field already exists in the model
        # So we're making this a no-op migration
    ]
