# Generated by Django 5.1.7 on 2025-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="iso_code_3",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
